# Generated by Django 4.0.3 on 2022-04-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogtags_blogpage_categories_blogpage_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
