name: CI/CD

on:
  push:
    branches: [ main, feat/*, fix/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    defaults:
      run:
        working-directory: ./app
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: app
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --system --dev --ignore-pipfile
    - name: Run Tests
      run: |
        python manage.py test
    - name: Tap Step
      run: |
        git --version
        pwd
        ls -la
    - name: Deploy
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "nguyenhoalaw" #Must be unique in Heroku
        heroku_email: "ntnhat.d@gmail.com"
        appdir: app
        procfile: |
          web: gunicorn nguyenhoalaw.wsgi
          release: python manage.py migrate
        run: |
          git --version
          pwd
          ls -la
    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: cms
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
